# Generated by Django 5.2 on 2025-05-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('colaborador', 'Colaborador'), ('gestor', 'Gestor')], default='colaborador', max_length=20),
        ),
    ]
