# Generated by Django 5.2 on 2025-12-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_group_members_and_add_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('membro', 'Membro'), ('admin', 'Administrador'), ('moderador', 'Moderador')], default='membro', max_length=20),
        ),
    ]
