# Generated by Django 5.2 on 2025-12-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_documentview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentview',
            unique_together=set(),
        ),
    ]
