# Generated by Django 5.2 on 2025-12-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_documentview_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='views',
        ),
    ]
