# Generated by Django 5.2 on 2025-12-06 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_document_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentview',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.document'),
        ),
    ]
